//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACAT.Lib.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACAT.Lib.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa ááá
        ///aaaaa ááááá
        ///aaallati ááállati
        ///aaallj ááállj
        ///aachentol aachentől
        ///aadom áadom
        ///aagykupolajat aagykupoláját
        ///aak áak
        ///aalstnal aalstnál
        ///aar aár
        ///aarhusbol aarhusból
        ///aartek aarték
        ///abace ábácé
        ///abachanak abachának
        ///abad abád
        ///abadani abadáni
        ///abadiak abadiák
        ///abadszalok abádszalók
        ///abadszaloki abádszalóki
        ///abadszalokrol abádszalókról
        ///abajgatjak abajgatják
        ///abakanowiczrol abakanowiczról
        ///abakusznal abakusznál
        ///abalienalja abalienálja
        ///abalt abált
        ///abaltszalonna abáltszalonna
        ///aban ában
        ///abapuszta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AccentDictionary_hu {
            get {
                return ResourceManager.GetString("AccentDictionary_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SplashScreenBg {
            get {
                object obj = ResourceManager.GetObject("SplashScreenBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
